export const env = {
    SHOPIFY_ACCESS_TOKEN: process.env.SHOPIFY_ACCESS_TOKEN || "",
    SHOPIFY_HOSTNAME: process.env.SHOPIFY_HOSTNAME,
    NEXT_PUBLIC_SHOPIFY_HOSTNAME: process.env.NEXT_PUBLIC_SHOPIFY_HOSTNAME,
    CACHE_TOKEN: process.env.CACHE_TOKEN
}