export const env = {
    SHOPIFY_ACCESS_TOKEN: process.env.SHOPIFY_ACCESS_TOKEN || "",
    SHOPIFY_HOSTNAME: process.env.SHOPIFY_HOSTNAME,
    NEXT_PUBLIC_SHOPIFY_HOSTNAME: process.env.NEXT_PUBLIC_SHOPIFY_HOSTNAME,
    CACHE_TOKEN: process.env.CACHE_TOKEN,
    SHOPIFY_GRAPHQL_ENDPOINT: process.env.SHOPIFY_GRAPHQL_ENDPOINT,
    HEADLESS_PRIVATE_ACCESS_TOKEN: process.env.HEADLESS_PRIVATE_ACCESS_TOKEN
}